name: Backend deploy

on:
  push:
    branches:
      - dev
      - main

jobs:
  docker_image_build:
    name: Docker image build
    runs-on: ubuntu-latest

    steps:
      - name: Set branch name
        run: echo "GIT_BRANCH=$(echo ${GITHUB_REF#refs/heads/})" >> $GITHUB_ENV

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ghcr.io/${{ github.event.repository.name }}:${{ env.GIT_BRANCH }}

  update_backend_instances:
    name: Update backend instances
    runs-on: ubuntu-latest
    needs: docker_image_build

    steps:
      - uses: actions/checkout@v3

      - name: Set environment name
        run: echo "ENVIRONMENT=$(echo ${GITHUB_REF#refs/heads/} | sed 's/main/production/')" >> $GITHUB_ENV

      - name: Get ssh private key
        run: |
          echo "$SSH_PRIVATE_KEY" > ssh_private_key
          chmod 600 ssh_private_key
        working-directory: infrastructure
        env:
          SSH_PRIVATE_KEY: ${{ secrets[format('SSH_PRIVATE_KEY__{0}', env.ENVIRONMENT)] }} # secret

      - name: Install ansible
        run: |
          sudo apt update
          sudo apt install -y software-properties-common
          sudo add-apt-repository --yes --update ppa:ansible/ansible
          sudo apt install -y ansible

      - name: Install docker ansible module
        run: |
          ansible-galaxy collection install --timeout 120 --verbose community.docker

      - name: Run ansible
        run: |
          ./scripts/ansible-playbook.sh $ENVIRONMENT ./ssh_private_key
        working-directory: infrastructure
